// Code generated by protoc-gen-go. DO NOT EDIT.
// source: dummy2.proto
package pb

import (
	"context"

	"github.com/grpc-ecosystem/grpc-gateway/runtime"

	"go.saastack.io/protoc-gen-grpc-wrapper/middleware"

	"google.golang.org/grpc"
)

type wrapperDummy2 struct {
	client Dummy2Client
}

func NewDummy2HandlerWrapper(client Dummy2Client) Dummy2Client {
	return &wrapperDummy2{client: client}
}

func RegisterDummy2HandlerClientWrapper(ctx context.Context, mux *runtime.ServeMux, client Dummy2Client) error {
	return RegisterDummy2HandlerClient(ctx, mux, NewDummy2HandlerWrapper(client))
}

func (g *wrapperDummy2) GetDummy2Method1(ctx context.Context, in *GetDummy2Method1Request, opts ...grpc.CallOption) (*Dummy2Method1Object, error) {
	middleware.MaskFieldsFromRequest(in)
	var resp, err = g.client.GetDummy2Method1(ctx, in, opts...)
	if err != nil {
		return nil, err
	}
	middleware.MaskFieldsFromResponse(resp)
	return resp, nil
}

func (g *wrapperDummy2) GetDummy2Method2(ctx context.Context, in *GetDummy2Method2Request, opts ...grpc.CallOption) (*Dummy2Method2Object, error) {
	middleware.MaskFieldsFromRequest(in)
	var resp, err = g.client.GetDummy2Method2(ctx, in, opts...)
	if err != nil {
		return nil, err
	}
	middleware.MaskFieldsFromResponse(resp)
	return resp, nil
}
