// Code generated by protoc-gen-go. DO NOT EDIT.
// source: dummy2.proto
package pb

import (
	"go.saastack.io/protoc-gen-grpc-wrapper/middleware"
	"go.uber.org/fx"
)

// UnregisteredMethods_Dummy2 will provide list of methods to un register from GRPC server
var UnregisteredMethods_Dummy2 = fx.Provide(
	fx.Annotated{
		Group:  "methods",
		Target: _Dummy2_methodsList,
	},
)

func _Dummy2_methodsList() middleware.UnregisteredMethods {
	return middleware.UnregisteredMethods{
		"/dummy_2.Dummy2/GetDummy2Method1",
		"/dummy_2.Dummy2/GetDummy2Method2",
	}
}

// MaskFieldsFromGrpcResonse will mask null the marked fields from response
func (m *Dummy2Method1Object) MaskFieldsFromGrpcResonse() {
	if m == nil {
		return
	}

}

// MaskFieldsFromGrpcRequest will mask null the marked fields from request
func (m *Dummy2Method1Object) MaskFieldsFromGrpcRequest() {
	if m == nil {
		return
	}

}

// MaskFieldsFromGrpcResonse will mask null the marked fields from response
func (m *GetDummy2Method1Request) MaskFieldsFromGrpcResonse() {
	if m == nil {
		return
	}

}

// MaskFieldsFromGrpcRequest will mask null the marked fields from request
func (m *GetDummy2Method1Request) MaskFieldsFromGrpcRequest() {
	if m == nil {
		return
	}

}

// MaskFieldsFromGrpcResonse will mask null the marked fields from response
func (m *Dummy2Method2Object) MaskFieldsFromGrpcResonse() {
	if m == nil {
		return
	}

}

// MaskFieldsFromGrpcRequest will mask null the marked fields from request
func (m *Dummy2Method2Object) MaskFieldsFromGrpcRequest() {
	if m == nil {
		return
	}

}

// MaskFieldsFromGrpcResonse will mask null the marked fields from response
func (m *GetDummy2Method2Request) MaskFieldsFromGrpcResonse() {
	if m == nil {
		return
	}

}

// MaskFieldsFromGrpcRequest will mask null the marked fields from request
func (m *GetDummy2Method2Request) MaskFieldsFromGrpcRequest() {
	if m == nil {
		return
	}

}
