// Code generated by recaptcha. DO NOT EDIT.

package pb

import (
	"context"
	"recaptcha_module"
)

// Service: Dummy1

type dummy1RecaptchaServer struct {
	Dummy1Server
	recaptchaServer recaptcha_module.ReCaptchaServer
}

func NewDummy1RecaptchaServer(srv Dummy1Server, rSrv recaptcha_module.ReCaptchaServer) Dummy1Server {
	return &dummy1RecaptchaServer{
		Dummy1Server:    srv,
		recaptchaServer: rSrv,
	}
}

// Method: GetDummy1Method1 (This method requires reCAPTCHA verification)
func (s *dummy1RecaptchaServer) GetDummy1Method1(ctx context.Context, req *GetDummy1Method1Request) (*Dummy1Method1Object, error) {

	if err := s.recaptchaServer.ValidateRecaptcha(ctx); err != nil {
		return nil, err
	}

	return s.Dummy1Server.GetDummy1Method1(ctx, req)
}

// Method: GetDummy1Method2 (This method does not require reCAPTCHA verification)
