// Code generated by protoc-gen-go. DO NOT EDIT.
// source: dummy1.proto
package pb

import (
	"go.saastack.io/protoc-gen-grpc-wrapper/middleware"
	"go.uber.org/fx"
)

// UnregisteredMethods_Dummy1 will provide list of methods to un register from GRPC server
var UnregisteredMethods_Dummy1 = fx.Provide(
	fx.Annotated{
		Group:  "methods",
		Target: _Dummy1_methodsList,
	},
)

func _Dummy1_methodsList() middleware.UnregisteredMethods {
	return middleware.UnregisteredMethods{
		"/dummy_1.Dummy1/GetDummy1Method1",
		"/dummy_1.Dummy1/GetDummy1Method2",
	}
}

// MaskFieldsFromGrpcResonse will mask null the marked fields from response
func (m *Dummy1Method1Object) MaskFieldsFromGrpcResonse() {
	if m == nil {
		return
	}

}

// MaskFieldsFromGrpcRequest will mask null the marked fields from request
func (m *Dummy1Method1Object) MaskFieldsFromGrpcRequest() {
	if m == nil {
		return
	}

}

// MaskFieldsFromGrpcResonse will mask null the marked fields from response
func (m *GetDummy1Method1Request) MaskFieldsFromGrpcResonse() {
	if m == nil {
		return
	}

}

// MaskFieldsFromGrpcRequest will mask null the marked fields from request
func (m *GetDummy1Method1Request) MaskFieldsFromGrpcRequest() {
	if m == nil {
		return
	}

}

// MaskFieldsFromGrpcResonse will mask null the marked fields from response
func (m *Dummy1Method2Object) MaskFieldsFromGrpcResonse() {
	if m == nil {
		return
	}

}

// MaskFieldsFromGrpcRequest will mask null the marked fields from request
func (m *Dummy1Method2Object) MaskFieldsFromGrpcRequest() {
	if m == nil {
		return
	}

}

// MaskFieldsFromGrpcResonse will mask null the marked fields from response
func (m *GetDummy1Method2Request) MaskFieldsFromGrpcResonse() {
	if m == nil {
		return
	}

}

// MaskFieldsFromGrpcRequest will mask null the marked fields from request
func (m *GetDummy1Method2Request) MaskFieldsFromGrpcRequest() {
	if m == nil {
		return
	}

}
