// Code generated by protoc-gen-go. DO NOT EDIT.
// source: dummy1.proto

package pb

import (
	context "context"
	fmt "fmt"
	math "math"

	proto "github.com/golang/protobuf/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Dummy1Method1Object struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Dummy1Method1Object) Reset()         { *m = Dummy1Method1Object{} }
func (m *Dummy1Method1Object) String() string { return proto.CompactTextString(m) }
func (*Dummy1Method1Object) ProtoMessage()    {}
func (*Dummy1Method1Object) Descriptor() ([]byte, []int) {
	return fileDescriptor_17a044dbfe859bc6, []int{0}
}

func (m *Dummy1Method1Object) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Dummy1Method1Object.Unmarshal(m, b)
}
func (m *Dummy1Method1Object) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Dummy1Method1Object.Marshal(b, m, deterministic)
}
func (m *Dummy1Method1Object) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Dummy1Method1Object.Merge(m, src)
}
func (m *Dummy1Method1Object) XXX_Size() int {
	return xxx_messageInfo_Dummy1Method1Object.Size(m)
}
func (m *Dummy1Method1Object) XXX_DiscardUnknown() {
	xxx_messageInfo_Dummy1Method1Object.DiscardUnknown(m)
}

var xxx_messageInfo_Dummy1Method1Object proto.InternalMessageInfo

func (m *Dummy1Method1Object) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Dummy1Method1Object) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type GetDummy1Method1Request struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetDummy1Method1Request) Reset()         { *m = GetDummy1Method1Request{} }
func (m *GetDummy1Method1Request) String() string { return proto.CompactTextString(m) }
func (*GetDummy1Method1Request) ProtoMessage()    {}
func (*GetDummy1Method1Request) Descriptor() ([]byte, []int) {
	return fileDescriptor_17a044dbfe859bc6, []int{1}
}

func (m *GetDummy1Method1Request) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetDummy1Method1Request.Unmarshal(m, b)
}
func (m *GetDummy1Method1Request) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetDummy1Method1Request.Marshal(b, m, deterministic)
}
func (m *GetDummy1Method1Request) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetDummy1Method1Request.Merge(m, src)
}
func (m *GetDummy1Method1Request) XXX_Size() int {
	return xxx_messageInfo_GetDummy1Method1Request.Size(m)
}
func (m *GetDummy1Method1Request) XXX_DiscardUnknown() {
	xxx_messageInfo_GetDummy1Method1Request.DiscardUnknown(m)
}

var xxx_messageInfo_GetDummy1Method1Request proto.InternalMessageInfo

func (m *GetDummy1Method1Request) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type Dummy1Method2Object struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Dummy1Method2Object) Reset()         { *m = Dummy1Method2Object{} }
func (m *Dummy1Method2Object) String() string { return proto.CompactTextString(m) }
func (*Dummy1Method2Object) ProtoMessage()    {}
func (*Dummy1Method2Object) Descriptor() ([]byte, []int) {
	return fileDescriptor_17a044dbfe859bc6, []int{2}
}

func (m *Dummy1Method2Object) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Dummy1Method2Object.Unmarshal(m, b)
}
func (m *Dummy1Method2Object) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Dummy1Method2Object.Marshal(b, m, deterministic)
}
func (m *Dummy1Method2Object) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Dummy1Method2Object.Merge(m, src)
}
func (m *Dummy1Method2Object) XXX_Size() int {
	return xxx_messageInfo_Dummy1Method2Object.Size(m)
}
func (m *Dummy1Method2Object) XXX_DiscardUnknown() {
	xxx_messageInfo_Dummy1Method2Object.DiscardUnknown(m)
}

var xxx_messageInfo_Dummy1Method2Object proto.InternalMessageInfo

func (m *Dummy1Method2Object) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Dummy1Method2Object) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type GetDummy1Method2Request struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetDummy1Method2Request) Reset()         { *m = GetDummy1Method2Request{} }
func (m *GetDummy1Method2Request) String() string { return proto.CompactTextString(m) }
func (*GetDummy1Method2Request) ProtoMessage()    {}
func (*GetDummy1Method2Request) Descriptor() ([]byte, []int) {
	return fileDescriptor_17a044dbfe859bc6, []int{3}
}

func (m *GetDummy1Method2Request) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetDummy1Method2Request.Unmarshal(m, b)
}
func (m *GetDummy1Method2Request) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetDummy1Method2Request.Marshal(b, m, deterministic)
}
func (m *GetDummy1Method2Request) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetDummy1Method2Request.Merge(m, src)
}
func (m *GetDummy1Method2Request) XXX_Size() int {
	return xxx_messageInfo_GetDummy1Method2Request.Size(m)
}
func (m *GetDummy1Method2Request) XXX_DiscardUnknown() {
	xxx_messageInfo_GetDummy1Method2Request.DiscardUnknown(m)
}

var xxx_messageInfo_GetDummy1Method2Request proto.InternalMessageInfo

func (m *GetDummy1Method2Request) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func init() {
	proto.RegisterType((*Dummy1Method1Object)(nil), "dummy_1.Dummy1Method1Object")
	proto.RegisterType((*GetDummy1Method1Request)(nil), "dummy_1.GetDummy1Method1Request")
	proto.RegisterType((*Dummy1Method2Object)(nil), "dummy_1.Dummy1Method2Object")
	proto.RegisterType((*GetDummy1Method2Request)(nil), "dummy_1.GetDummy1Method2Request")
}

func init() { proto.RegisterFile("dummy1.proto", fileDescriptor_17a044dbfe859bc6) }

var fileDescriptor_17a044dbfe859bc6 = []byte{
	// 253 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x49, 0x29, 0xcd, 0xcd,
	0xad, 0x34, 0xd4, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x07, 0xf3, 0xe2, 0x0d, 0xa5, 0x64,
	0x13, 0xf3, 0xf2, 0xf2, 0x4b, 0x12, 0x4b, 0x32, 0xf3, 0xf3, 0x8a, 0xf5, 0x91, 0xd8, 0x10, 0x75,
	0x52, 0x92, 0x45, 0xa9, 0xc9, 0x89, 0x05, 0x25, 0xc9, 0x19, 0x89, 0xfa, 0x70, 0x16, 0x44, 0x4a,
	0xc9, 0x92, 0x4b, 0xd8, 0x05, 0x6c, 0xa4, 0x6f, 0x6a, 0x49, 0x46, 0x7e, 0x8a, 0xa1, 0x7f, 0x52,
	0x56, 0x6a, 0x72, 0x89, 0x10, 0x1f, 0x17, 0x53, 0x66, 0x8a, 0x04, 0xa3, 0x02, 0xa3, 0x06, 0x67,
	0x10, 0x53, 0x66, 0x8a, 0x90, 0x10, 0x17, 0x4b, 0x5e, 0x62, 0x6e, 0xaa, 0x04, 0x13, 0x58, 0x04,
	0xcc, 0x56, 0xd2, 0xe4, 0x12, 0x77, 0x4f, 0x2d, 0x41, 0xd1, 0x1d, 0x94, 0x5a, 0x58, 0x9a, 0x5a,
	0x8c, 0xa1, 0x1d, 0xdd, 0x16, 0x23, 0x8a, 0x6c, 0x31, 0xc2, 0x61, 0x8b, 0x51, 0x03, 0x13, 0x17,
	0x1b, 0x44, 0xa1, 0x50, 0x0d, 0x97, 0x00, 0xba, 0xdb, 0x84, 0x14, 0xf4, 0xa0, 0xc1, 0xa5, 0x87,
	0xc3, 0xd9, 0x52, 0x32, 0x70, 0x15, 0x58, 0xc2, 0x44, 0x49, 0xa3, 0x63, 0xab, 0x04, 0x63, 0xd3,
	0xe5, 0x27, 0x93, 0x99, 0xe4, 0x84, 0x64, 0xf4, 0xcb, 0x0c, 0xf5, 0xc1, 0x8a, 0x75, 0x0d, 0xf5,
	0x73, 0xc1, 0xca, 0x74, 0x0d, 0xf5, 0xab, 0x33, 0x53, 0x6c, 0xb5, 0xb4, 0x6a, 0x85, 0x2a, 0x30,
	0x6c, 0x37, 0xc2, 0x6d, 0xbb, 0x11, 0x7e, 0xdb, 0xa1, 0x61, 0xa5, 0xa4, 0x82, 0xc7, 0x66, 0x23,
	0x98, 0xcd, 0x4e, 0x6c, 0x51, 0x2c, 0x7a, 0xd6, 0x05, 0x49, 0x49, 0x6c, 0xe0, 0xd8, 0x35, 0x06,
	0x04, 0x00, 0x00, 0xff, 0xff, 0xa5, 0xe3, 0xc4, 0x47, 0x30, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Dummy1Client is the client API for Dummy1 service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type Dummy1Client interface {
	GetDummy1Method1(ctx context.Context, in *GetDummy1Method1Request, opts ...grpc.CallOption) (*Dummy1Method1Object, error)
	GetDummy1Method2(ctx context.Context, in *GetDummy1Method2Request, opts ...grpc.CallOption) (*Dummy1Method2Object, error)
}

type dummy1Client struct {
	cc *grpc.ClientConn
}

func NewDummy1Client(cc *grpc.ClientConn) Dummy1Client {
	return &dummy1Client{cc}
}

func (c *dummy1Client) GetDummy1Method1(ctx context.Context, in *GetDummy1Method1Request, opts ...grpc.CallOption) (*Dummy1Method1Object, error) {
	out := new(Dummy1Method1Object)
	err := c.cc.Invoke(ctx, "/dummy_1.Dummy1/GetDummy1Method1", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dummy1Client) GetDummy1Method2(ctx context.Context, in *GetDummy1Method2Request, opts ...grpc.CallOption) (*Dummy1Method2Object, error) {
	out := new(Dummy1Method2Object)
	err := c.cc.Invoke(ctx, "/dummy_1.Dummy1/GetDummy1Method2", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Dummy1Server is the server API for Dummy1 service.
type Dummy1Server interface {
	GetDummy1Method1(context.Context, *GetDummy1Method1Request) (*Dummy1Method1Object, error)
	GetDummy1Method2(context.Context, *GetDummy1Method2Request) (*Dummy1Method2Object, error)
}

// UnimplementedDummy1Server can be embedded to have forward compatible implementations.
type UnimplementedDummy1Server struct {
}

func (*UnimplementedDummy1Server) GetDummy1Method1(ctx context.Context, req *GetDummy1Method1Request) (*Dummy1Method1Object, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetDummy1Method1 not implemented")
}
func (*UnimplementedDummy1Server) GetDummy1Method2(ctx context.Context, req *GetDummy1Method2Request) (*Dummy1Method2Object, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetDummy1Method2 not implemented")
}

func RegisterDummy1Server(s *grpc.Server, srv Dummy1Server) {
	s.RegisterService(&_Dummy1_serviceDesc, srv)
}

func _Dummy1_GetDummy1Method1_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDummy1Method1Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(Dummy1Server).GetDummy1Method1(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/dummy_1.Dummy1/GetDummy1Method1",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(Dummy1Server).GetDummy1Method1(ctx, req.(*GetDummy1Method1Request))
	}
	return interceptor(ctx, in, info, handler)
}

func _Dummy1_GetDummy1Method2_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDummy1Method2Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(Dummy1Server).GetDummy1Method2(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/dummy_1.Dummy1/GetDummy1Method2",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(Dummy1Server).GetDummy1Method2(ctx, req.(*GetDummy1Method2Request))
	}
	return interceptor(ctx, in, info, handler)
}

var _Dummy1_serviceDesc = grpc.ServiceDesc{
	ServiceName: "dummy_1.Dummy1",
	HandlerType: (*Dummy1Server)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetDummy1Method1",
			Handler:    _Dummy1_GetDummy1Method1_Handler,
		},
		{
			MethodName: "GetDummy1Method2",
			Handler:    _Dummy1_GetDummy1Method2_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "dummy1.proto",
}
